-- MySQL Script generated by MySQL Workbench
-- Fri Nov 21 18:45:25 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Usuario` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Usuario` (
  `id_pk` INT NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `senha` VARCHAR(255) NOT NULL,
  `permissao` VARCHAR(5) NOT NULL,
  PRIMARY KEY (`id_pk`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Categoria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Categoria` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Categoria` (
  `id_pk` INT NOT NULL,
  `nome` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_pk`),
  UNIQUE INDEX `nome_UNIQUE` (`nome` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Peca`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Peca` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Peca` (
  `id_pk` INT NOT NULL,
  `nome` VARCHAR(255) NOT NULL,
  `estoque` INT NOT NULL,
  `imagem` VARCHAR(255) NULL,
  `Categoria_id_pk` INT NOT NULL,
  PRIMARY KEY (`id_pk`),
  INDEX `fk_Peca_Categoria_idx` (`Categoria_id_pk` ASC) VISIBLE,
  CONSTRAINT `fk_Peca_Categoria`
    FOREIGN KEY (`Categoria_id_pk`)
    REFERENCES `mydb`.`Categoria` (`id_pk`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Venda`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Venda` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Venda` (
  `id_pk` INT NOT NULL,
  `data_horario` DATETIME NOT NULL,
  PRIMARY KEY (`id_pk`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Reposicao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Reposicao` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Reposicao` (
  `id_pk` INT NOT NULL,
  `data_horario` DATETIME NOT NULL,
  PRIMARY KEY (`id_pk`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Venda_tem_Peca`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Venda_tem_Peca` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Venda_tem_Peca` (
  `Venda_id_fk_pk` INT NOT NULL,
  `Peca_id_fk_pk` INT NOT NULL,
  `preco` DECIMAL(2) NOT NULL,
  `quantidade` INT NOT NULL,
  PRIMARY KEY (`Venda_id_fk_pk`, `Peca_id_fk_pk`),
  INDEX `fk_Venda_has_Peca_Peca1_idx` (`Peca_id_fk_pk` ASC) VISIBLE,
  INDEX `fk_Venda_has_Peca_Venda1_idx` (`Venda_id_fk_pk` ASC) VISIBLE,
  CONSTRAINT `fk_Venda_has_Peca_Venda1`
    FOREIGN KEY (`Venda_id_fk_pk`)
    REFERENCES `mydb`.`Venda` (`id_pk`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Venda_has_Peca_Peca1`
    FOREIGN KEY (`Peca_id_fk_pk`)
    REFERENCES `mydb`.`Peca` (`id_pk`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Reposicao_tem_Peca`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Reposicao_tem_Peca` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Reposicao_tem_Peca` (
  `Reposicao_id_fk_pk` INT NOT NULL,
  `Peca_id_fk_pk` INT NOT NULL,
  `preco` DECIMAL(2) NOT NULL,
  `quantidade` INT NOT NULL,
  PRIMARY KEY (`Reposicao_id_fk_pk`, `Peca_id_fk_pk`),
  INDEX `fk_Reposicao_has_Peca_Peca1_idx` (`Peca_id_fk_pk` ASC) VISIBLE,
  INDEX `fk_Reposicao_has_Peca_Reposicao1_idx` (`Reposicao_id_fk_pk` ASC) VISIBLE,
  CONSTRAINT `fk_Reposicao_has_Peca_Reposicao1`
    FOREIGN KEY (`Reposicao_id_fk_pk`)
    REFERENCES `mydb`.`Reposicao` (`id_pk`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Reposicao_has_Peca_Peca1`
    FOREIGN KEY (`Peca_id_fk_pk`)
    REFERENCES `mydb`.`Peca` (`id_pk`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
